server:
  port: 8443
spring:
  kafka:
    bootstrap-servers: 10.100.208.65:9092
  redis:
    password: Avaya123
    port: 6379
    host: 10.100.20.171
topic:
  writer-topic: writer_generator_topic
  article-topic: article_generator_topic
  article-response-topic: article_response_topic
  writer-response-topic: writer_response_topic
  schema:
    registry:
      url: http://10.99.85.211:8081